- name: Install nginx using amazon-linux-extras
  shell: "amazon-linux-extras install nginx1 -y"
  args:
    creates: /usr/sbin/nginx

- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy nginx configuration
  template:
    src: nginx_frontend.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
