---
- name: Configure Apache and Fetch Metadata
  hosts: ec2
  become: true
  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

    - name: Ensure nginx is stopped and disabled
      systemd:
        name: nginx
        state: stopped
        enabled: false
      failed_when: false

    - name: Install httpd
      dnf:
        name: httpd
        state: present

    - name: Start and enable httpd
      systemd:
        name: httpd
        state: started
        enabled: true

    - name: Get IMDSv2 Token
      uri:
        url: http://169.254.169.254/latest/api/token
        method: PUT
        headers:
          X-aws-ec2-metadata-token-ttl-seconds: "21600"
        return_content: true
      register: token_response

    - name: Fetch Public IP via IMDSv2
      uri:
        url: http://169.254.169.254/latest/meta-data/public-ipv4
        headers:
          X-aws-ec2-metadata-token: "{{ token_response.content }}"
        return_content: true
      register: public_ip

    - name: Fetch Public Hostname via IMDSv2
      uri:
        url: http://169.254.169.254/latest/meta-data/public-hostname
        headers:
          X-aws-ec2-metadata-token: "{{ token_response.content }}"
        return_content: true
      register: public_hostname

    - name: Debug Public IP
      debug:
        msg: "The Public IP is {{ public_ip.content }}"

    - name: Restart httpd
      systemd:
        name: httpd
        state: restarted
